### ISSUE TITLE
Module not found: Can't resolve 'fs'

### ISSUE THREAD

**Issue by tylermcrobert** [princjef/get-system-fonts#17] opened 2020-11-19 19:00 UTC
I'm getting the error `Module not found: Can't resolve 'fs'` when using Next.JS. It's entirely possible I'm missing something.

**Comment by princjef** [comment] 2020-11-25 00:15
Hi @tylermcrobert, this package is only available in NodeJS-compatible runtimes as it requires access to the machine's filesystem to discover and list the fonts installed on the system. The error you're seeing is from the package trying to load node's built-in filesystem package.

**Comment by princjef** [comment] 2020-11-25 00:16
Closing as by design. Please feel free to reactivate if you have further questions/suggestions.

**Closed as completed by princjef** 2020-11-25 00:16 UTC
